apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-lh
  namespace: private
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 40Gi
