volume:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClassName: longhorn
  existingClaim: uptime-kuma-pvc
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
image:
  tag: "2.5.6"
  repository: louislam/uptime-kuma
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
service:
  type: ClusterIP
  port: 3001
